apiVersion: v1
kind: Service
metadata:
  name: app-service

spec:
  selector:
    app: app-deployment
    tier: frontend
  
  type: LoadBalancer
  ports:

    - port: 80
      targetPort: 80
      protocol: TCP
      